language: python
python:
  - "2.7"
# command to install dependencies
before_install: sudo apt-get install -qq libjpeg8-dev
install: "pip install -r requirements.txt"
services:
 - postgresql
 - memcached
before_script:
 - psql -U postgres -c "CREATE USER django WITH PASSWORD 'djangopass' SUPERUSER;"
 - createdb photoapp
# command to run tests
script: python manage.py test