language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
services: postgresql
before_script:
 - psql -c "CREATE USER django WITH PASSWORD 'djangopass' SUPERUSER;"
 - cd PhotoApp
# command to run tests
script: python manage.py test